import Head from 'next/head';
import { Main } from '../components';

function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <Main />
      </div>
    </>
  );
}

export default Home;
